### ISSUE TITLE
CI unit tests failure

### ISSUE THREAD

**Issue by jerome-benoit** [pioardi/poolifier#160]
**Describe the bug**

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:705:16)
    at Worker.send (internal/cluster/worker.js:46:10)
    at ClusterWorker.sendToMainWorker (/home/runner/work/poolifier/poolifier/lib/worker/cluster-worker.js:21:282)
    at ClusterWorker.checkAlive (/home/runner/work/poolifier/poolifier/lib/worker/abstract-worker.js:27:178)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:30:12)
    at process.emit (events.js:315:20)
    at processEmit [as emit] (/home/runner/work/poolifier/poolifier/node_modules/signal-exit/index.js:161:32)
    at internal/child_process.js:709:35
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```

**Steps to reproduce the behavior**

Do a test PR on the repository 

**Expected behavior**

Unit tests should work on GitHub CI
GitHub shall not mark the unit tests run as successful

**Info**

| Tool      | Version       |
| --------- | ------------- |
| Poolifier | v2.x.x        |
| Node      | v1x.x.x       |
| OS        | linux         |

**Comment by jerome-benoit** [comment]
It only happens with node.js 14.x.x version.

**Comment by Shinigami92** [comment]
Seems to also occur in node.js 12.0.0
https://github.com/pioardi/poolifier/runs/1905645721?check_suite_focus=true#step:7:45

**Comment by pioardi** [comment]
I guess is just random bro

**Comment by pioardi** [comment]
I think that this is because we execute ` worker.kill()` but we should first clear the interval when the worker is dynamic.
We just need to understand how ( destroyWorker method override could be useful )

**Comment by pioardi** [comment]
The initial behavior described by @jerome-benoit  is fixed.
We need now to fix this other error:

```
events.js:291
94
      throw er; // Unhandled 'error' event
95
      ^
96

97
Error: write EPIPE
98
    at process.target._send (internal/child_process.js:807:20)
99
    at process.target.send (internal/child_process.js:678:19)
100
    at Worker.send (internal/cluster/worker.js:45:28)
101
    at ClusterWorker.sendToMainWorker (/home/runner/work/poolifier/poolifier/lib/worker/cluster-worker.js:21:282)
102
    at ClusterWorker.checkAlive (/home/runner/work/poolifier/poolifier/lib/worker/abstract-worker.js:27:178)
103
    at listOnTimeout (internal/timers.js:554:17)
104
    at processTimers (internal/timers.js:497:7)
105
Emitted 'error' event on Worker instance at:
106
    at process.<anonymous> (internal/cluster/worker.js:29:12)
107
    at process.emit (events.js:314:20)
108
    at processEmit [as emit] (/home/runner/work/poolifier/poolifier/node_modules/signal-exit/index.js:161:32)
109
    at internal/child_process.js:811:39
110
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
111
  errno: 'EPIPE',
112
  code: 'EPIPE',
113
  syscall: 'write'
```

**Comment by pioardi** [comment]
The issue were present on our unit tests, we were not using our pool methods to clean up the child processes, so when mocha terminated the tests the shutdown was not graceful.
What we did is shutdown the  cluster pools gracefully before to finish our test cases.

Issue should be now totally fixed, in future we should always destroy our pools after the tests to avoid similar issues.
